export const NEXT_STEP = 'NEXT_STEP';
export const PREV_STEP = 'PREV_STEP';
export const UPDATE_NEW_RECIPE = 'UPDATE_NEW_RECIPE';
export const EDIT_SECTION = 'EDIT_SECTION';
export const FINISH_EDITING = 'FINISH_EDITING';
export const SAVE_RECIPE = 'SAVE_RECIPE';
export const LOAD_ALL_RECIPES = 'LOAD_ALL_RECIPES';
export const SELECT_MAIN_IMAGE = 'SELECT_MAIN_IMAGE';
